"""
This type stub file was generated by pyright.
"""

from .common import FileDownloader

class BunnyCdnFD(FileDownloader):
    """
    Downloads from BunnyCDN with required pings
    Note, this is not a part of public API, and will be removed without notice.
    DO NOT USE
    """
    def real_download(self, filename, info_dict):
        ...
    
    def ping_thread(self, stop_event, url, headers, secret, context_id): # -> None:
        ...
    


