"""
This type stub file was generated by pyright.
"""

from .common import FileDownloader

class NiconicoLiveFD(FileDownloader):
    """ Downloads niconico live without being stopped """
    def real_download(self, filename, info_dict): # -> tuple[Literal[True], Literal[False]] | tuple[Any, Literal[True]]:
        ...
    


