"""
This type stub file was generated by pyright.
"""

from .common import FileDownloader

class SoopVodFD(FileDownloader):
    """
    Downloads Soop subscription VODs with required cookie refresh requests
    Note, this is not a part of public API, and will be removed without notice.
    DO NOT USE
    """
    def real_download(self, filename, info_dict):
        ...
    


