"""
This type stub file was generated by pyright.
"""

def what(file=..., h=...): # -> Literal['webp', 'png', 'jpeg', 'gif'] | None:
    """Detect format of image (Currently supports jpeg, png, webp, gif only)
    Ref: https://github.com/python/cpython/blob/3.11/Lib/imghdr.py
    Ref: https://www.w3.org/Graphics/JPEG/itu-t81.pdf
    """
    ...

