"""
This type stub file was generated by pyright.
"""

import abc
import dataclasses
import functools
from ._utils import version_tuple

_FALLBACK_PATHEXT = ...
@dataclasses.dataclass(frozen=True)
class JsRuntimeInfo:
    name: str
    path: str
    version: str
    version_tuple: tuple[int, ...]
    supported: bool = ...


class JsRuntime(abc.ABC):
    def __init__(self, path=...) -> None:
        ...
    
    @functools.cached_property
    def info(self) -> JsRuntimeInfo | None:
        ...
    


class DenoJsRuntime(JsRuntime):
    MIN_SUPPORTED_VERSION = ...


class BunJsRuntime(JsRuntime):
    MIN_SUPPORTED_VERSION = ...


class NodeJsRuntime(JsRuntime):
    MIN_SUPPORTED_VERSION = ...


class QuickJsRuntime(JsRuntime):
    MIN_SUPPORTED_VERSION = ...


