"""
This type stub file was generated by pyright.
"""

import typing

if typing.TYPE_CHECKING:
    T = typing.TypeVar('T')
def random_user_agent(): # -> str:
    ...

class HTTPHeaderDict(dict):
    """
    Store and access keys case-insensitively.
    The constructor can take multiple dicts, in which keys in the latter are prioritised.

    Retains a case sensitive mapping of the headers, which can be accessed via `.sensitive()`.
    """
    def __new__(cls, *args: typing.Any, **kwargs: typing.Any) -> typing.Self:
        ...
    
    def __init__(self, /, *args, **kwargs) -> None:
        ...
    
    def sensitive(self, /) -> dict[str, str]:
        ...
    
    def __contains__(self, key: str, /) -> bool:
        ...
    
    def __delitem__(self, key: str, /) -> None:
        ...
    
    def __getitem__(self, key, /) -> str:
        ...
    
    def __ior__(self, other, /): # -> _NotImplementedType | None:
        ...
    
    def __or__(self, other, /) -> typing.Self:
        ...
    
    def __ror__(self, other, /) -> typing.Self:
        ...
    
    def __setitem__(self, key: str, value, /) -> None:
        ...
    
    def clear(self, /) -> None:
        ...
    
    def copy(self, /) -> typing.Self:
        ...
    
    @typing.overload
    def get(self, key: str, /) -> str | None:
        ...
    
    @typing.overload
    def get(self, key: str, /, default: T) -> str | T:
        ...
    
    def get(self, key, /, default=...): # -> None:
        ...
    
    @typing.overload
    def pop(self, key: str, /) -> str:
        ...
    
    @typing.overload
    def pop(self, key: str, /, default: T) -> str | T:
        ...
    
    def pop(self, key, /, default=...):
        ...
    
    def popitem(self) -> tuple[str, str]:
        ...
    
    @typing.overload
    def setdefault(self, key: str, /) -> str:
        ...
    
    @typing.overload
    def setdefault(self, key: str, /, default) -> str:
        ...
    
    def setdefault(self, key, /, default=...) -> str:
        ...
    
    def update(self, other, /, **kwargs) -> None:
        ...
    


std_headers = ...
def clean_proxies(proxies: dict, headers: HTTPHeaderDict): # -> None:
    ...

def clean_headers(headers: HTTPHeaderDict): # -> None:
    ...

def remove_dot_segments(path): # -> LiteralString:
    ...

def escape_rfc3986(s): # -> str:
    """Escape non-ASCII characters as suggested by RFC 3986"""
    ...

def normalize_url(url):
    """Normalize URL as suggested by RFC 3986"""
    ...

def select_proxy(url, proxies): # -> list[Any] | type[NO_DEFAULT] | dict[Any, Any] | None:
    """Unified proxy selector for all backends"""
    ...

