"""
This type stub file was generated by pyright.
"""

class ProgressCalculator:
    SAMPLING_WINDOW = ...
    SAMPLING_RATE = ...
    GRACE_PERIOD = ...
    def __init__(self, initial: int) -> None:
        ...
    
    @property
    def total(self): # -> int | None:
        ...
    
    @total.setter
    def total(self, value: int | None): # -> None:
        ...
    
    def thread_reset(self): # -> None:
        ...
    
    def update(self, size: int | None): # -> None:
        ...
    


class SmoothValue:
    def __init__(self, initial: float | None, smoothing: float) -> None:
        ...
    
    def set(self, value: float): # -> None:
        ...
    
    def reset(self): # -> None:
        ...
    


