"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class BlackboardCollaborateIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class BlackboardCollaborateLaunchIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


