"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class CamFMShowIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class CamFMEpisodeIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


