"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor
from .theplatform import ThePlatformFeedIE

class CBSBaseIE(ThePlatformFeedIE):
    ...


class CBSIE(CBSBaseIE):
    _WORKING = ...
    _VALID_URL = ...
    _TESTS = ...


class ParamountPressExpressIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


