"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class CineverseBaseIE(InfoExtractor):
    _VALID_URL_BASE = ...


class CineverseIE(CineverseBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class CineverseDetailsIE(CineverseBaseIE):
    _VALID_URL = ...
    _TESTS = ...


