"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class CNNIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class CNNIndonesiaIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


