"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class ElementorEmbedIE(InfoExtractor):
    _VALID_URL = ...
    _WEBPAGE_TESTS = ...
    _WIDGET_REGEX = ...


