"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class FrontoBaseIE(InfoExtractor):
    ...


class FrontroVideoBaseIE(FrontoBaseIE):
    _CHANNEL_ID = ...


class FrontroGroupBaseIE(FrontoBaseIE):
    _CHANNEL_ID = ...
    _VIDEO_EXTRACTOR = ...
    _VIDEO_URL_TMPL = ...


