"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class HollywoodReporterIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class HollywoodReporterPlaylistIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


