"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class HSEShowBaseIE(InfoExtractor):
    _GEO_COUNTRIES = ...


class HSEShowIE(HSEShowBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class HSEProductIE(HSEShowBaseIE):
    _VALID_URL = ...
    _TESTS = ...


