"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class HungamaBaseIE(InfoExtractor):
    ...


class HungamaIE(HungamaBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class HungamaSongIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class HungamaAlbumPlaylistIE(HungamaBaseIE):
    _VALID_URL = ...
    _TESTS = ...


