"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class Kenh14VideoIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class Kenh14PlaylistIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


