"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class LRTStreamIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class LRTVODIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class LRTRadioIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


