"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class LSMLREmbedIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class LSMLTVEmbedIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class LSMReplayIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


