"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class MedialaanBaseIE(InfoExtractor):
    ...


class MedialaanIE(MedialaanBaseIE):
    _VALID_URL = ...
    _TESTS = ...
    _WEBPAGE_TESTS = ...


