"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class MixlrIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class MixlrRecoringIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


