"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class NetAppBaseIE(InfoExtractor):
    _BC_URL = ...


class NetAppVideoIE(NetAppBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class NetAppCollectionIE(NetAppBaseIE):
    _VALID_URL = ...
    _TESTS = ...


