"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class PiramideTVIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class PiramideTVChannelIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


