"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class RadioComercialIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class RadioComercialPlaylistIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


