"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class RinseFMBaseIE(InfoExtractor):
    _API_BASE = ...


class RinseFMIE(RinseFMBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class RinseFMArtistPlaylistIE(RinseFMBaseIE):
    _VALID_URL = ...
    _TESTS = ...


