"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class RozhlasIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class RozhlasBaseIE(InfoExtractor):
    ...


class RozhlasVltavaIE(RozhlasBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class MujRozhlasIE(RozhlasBaseIE):
    _VALID_URL = ...
    _TESTS = ...


