"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class RTVCPlayBaseIE(InfoExtractor):
    _BASE_VALID_URL = ...


class RTVCPlayIE(RTVCPlayBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class RTVCPlayEmbedIE(RTVCPlayBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class RTVCKalturaIE(RTVCPlayBaseIE):
    _VALID_URL = ...
    _TESTS = ...


