"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class S4CIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class S4CSeriesIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


