"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

def is_dst(date):
    ...

def rfc3339_to_atende(date): # -> int:
    ...

class SejmIE(InfoExtractor):
    _VALID_URL = ...
    IE_NAME = ...
    _TESTS = ...


