"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class SovietsClosetBaseIE(InfoExtractor):
    MEDIADELIVERY_REFERER = ...
    def parse_nuxt_jsonp(self, nuxt_jsonp_url, video_id, name): # -> dict[Any, Any] | list[Any] | type[NO_DEFAULT]:
        ...
    
    def video_meta(self, video_id, game_name, category_name, episode_number, stream_date): # -> dict[str, Any | dict[str, str] | str | int | bool | None]:
        ...
    


class SovietsClosetIE(SovietsClosetBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class SovietsClosetPlaylistIE(SovietsClosetBaseIE):
    _VALID_URL = ...
    _TESTS = ...


