"""
This type stub file was generated by pyright.
"""

from .streaks import StreaksBaseIE

class TBSJPBaseIE(StreaksBaseIE):
    ...


class TBSJPEpisodeIE(TBSJPBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class TBSJPProgramIE(TBSJPBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class TBSJPPlaylistIE(TBSJPBaseIE):
    _VALID_URL = ...
    _TESTS = ...


