"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class TelecincoBaseIE(InfoExtractor):
    ...


class TelecincoIE(TelecincoBaseIE):
    IE_DESC = ...
    _VALID_URL = ...
    _TESTS = ...
    _ASTRO_ISLAND_RE = ...


