"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class TheGuardianPodcastIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class TheGuardianPodcastPlaylistIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


