"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class UlizaPlayerIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class UlizaPortalIE(InfoExtractor):
    IE_DESC = ...
    _VALID_URL = ...
    _TESTS = ...


