"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class VidyardBaseIE(InfoExtractor):
    _HEADERS = ...


class VidyardIE(VidyardBaseIE):
    _VALID_URL = ...
    _EMBED_REGEX = ...
    _TESTS = ...
    _WEBPAGE_TESTS = ...


