"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class VoxMediaVolumeIE(InfoExtractor):
    _VALID_URL = ...


class VoxMediaIE(InfoExtractor):
    _VALID_URL = ...
    _EMBED_REGEX = ...
    _TESTS = ...
    _WEBPAGE_TESTS = ...


