"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class VTVGoIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class VTVIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


