"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class YappyIE(InfoExtractor):
    _WORKING = ...
    _VALID_URL = ...
    _TESTS = ...


class YappyProfileIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


