"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class ZaikoBaseIE(InfoExtractor):
    ...


class ZaikoIE(ZaikoBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class ZaikoETicketIE(ZaikoBaseIE):
    _VALID_URL = ...
    _TESTS = ...


