"""
This type stub file was generated by pyright.
"""

import collections.abc
import typing

TYPE_CHECKING = ...
if TYPE_CHECKING:
    T = typing.TypeVar('T')
_ARRAY_TYPE_LOOKUP = ...
def parse_iter(parsed: typing.Any, /, *, revivers: dict[str, collections.abc.Callable[[list], typing.Any]] | None = ...): # -> Generator[TypeError | IndexError | ValueError, Any, float | None]:
    ...

def parse(parsed: typing.Any, /, *, revivers: dict[str, collections.abc.Callable[[typing.Any], typing.Any]] | None = ...): # -> Any:
    ...

