"""
This type stub file was generated by pyright.
"""

import typing
from collections.abc import Iterable
from yt_dlp.extractor.youtube.pot._provider import IEContentProvider, IEContentProviderLogger
from yt_dlp.extractor.youtube.pot.cache import CacheProviderPreference, CacheProviderWritePolicy, PoTokenCacheProvider, PoTokenCacheSpec, PoTokenCacheSpecProvider
from yt_dlp.extractor.youtube.pot.provider import PoTokenProvider, PoTokenRequest, PoTokenResponse, Preference

if typing.TYPE_CHECKING:
    ...
class YoutubeIEContentProviderLogger(IEContentProviderLogger):
    def __init__(self, ie, prefix, log_level: IEContentProviderLogger.LogLevel | None = ...) -> None:
        ...
    
    def trace(self, message: str): # -> None:
        ...
    
    def debug(self, message: str, *, once=...): # -> None:
        ...
    
    def info(self, message: str): # -> None:
        ...
    
    def warning(self, message: str, *, once=...): # -> None:
        ...
    
    def error(self, message: str, cause=...): # -> None:
        ...
    


class PoTokenCache:
    def __init__(self, logger: IEContentProviderLogger, cache_providers: list[PoTokenCacheProvider], cache_spec_providers: list[PoTokenCacheSpecProvider], cache_provider_preferences: list[CacheProviderPreference] | None = ...) -> None:
        ...
    
    def get(self, request: PoTokenRequest) -> PoTokenResponse | None:
        ...
    
    def store(self, request: PoTokenRequest, response: PoTokenResponse, write_policy: CacheProviderWritePolicy | None = ...): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    


class PoTokenRequestDirector:
    def __init__(self, logger: IEContentProviderLogger, cache: PoTokenCache) -> None:
        ...
    
    def register_provider(self, provider: PoTokenProvider): # -> None:
        ...
    
    def register_preference(self, preference: Preference): # -> None:
        ...
    
    def get_po_token(self, request: PoTokenRequest) -> str | None:
        ...
    
    def close(self): # -> None:
        ...
    


EXTRACTOR_ARG_PREFIX = ...
def initialize_pot_director(ie): # -> PoTokenRequestDirector:
    ...

def provider_display_list(providers: Iterable[IEContentProvider]): # -> str:
    ...

def clean_pot(po_token: str): # -> str:
    ...

def validate_response(response: PoTokenResponse | None): # -> bool:
    ...

def validate_cache_spec(spec: PoTokenCacheSpec): # -> bool:
    ...

