"""
This type stub file was generated by pyright.
"""

import abc
import enum
from yt_dlp.extractor.common import InfoExtractor
from yt_dlp.utils import classproperty

class IEContentProviderLogger(abc.ABC):
    class LogLevel(enum.IntEnum):
        TRACE = ...
        DEBUG = ...
        INFO = ...
        WARNING = ...
        ERROR = ...
    
    
    log_level = ...
    @abc.abstractmethod
    def trace(self, message: str): # -> None:
        ...
    
    @abc.abstractmethod
    def debug(self, message: str, *, once=...): # -> None:
        ...
    
    @abc.abstractmethod
    def info(self, message: str): # -> None:
        ...
    
    @abc.abstractmethod
    def warning(self, message: str, *, once=...): # -> None:
        ...
    
    @abc.abstractmethod
    def error(self, message: str, cause=...): # -> None:
        ...
    


class IEContentProviderError(Exception):
    def __init__(self, msg=..., expected=...) -> None:
        ...
    


class IEContentProvider(abc.ABC):
    PROVIDER_VERSION: str = ...
    BUG_REPORT_LOCATION: str = ...
    def __init__(self, ie: InfoExtractor, logger: IEContentProviderLogger, settings: dict[str, list[str]], *_, **__) -> None:
        ...
    
    @classmethod
    def __init_subclass__(cls, *, suffix=..., **kwargs): # -> None:
        ...
    
    @classproperty
    def PROVIDER_NAME(cls) -> str:
        ...
    
    @classproperty
    def BUG_REPORT_MESSAGE(cls): # -> str:
        ...
    
    @classproperty
    def PROVIDER_KEY(cls) -> str:
        ...
    
    @abc.abstractmethod
    def is_available(self) -> bool:
        """
        Check if the provider is available (e.g. all required dependencies are available)
        This is used to determine if the provider should be used and to provide debug information.

        IMPORTANT: This method should not make any network requests or perform any expensive operations.
         It is called multiple times.
        """
        ...
    
    def close(self): # -> None:
        ...
    


class BuiltinIEContentProvider(IEContentProvider, abc.ABC):
    PROVIDER_VERSION = ...
    BUG_REPORT_MESSAGE = ...


def configuration_arg(config, key, default=..., *, casesense=...): # -> type[NO_DEFAULT] | list[Any]:
    """
    @returns            A list of values for the setting given by "key"
                        or "default" if no such key is present
    @param config       The configuration dictionary
    @param default      The default value to return when the key is not present (default: [])
    @param casesense    When false, the values are converted to lower case
    """
    ...

def register_provider_generic(provider, base_class, registry):
    """Generic function to register a provider class"""
    ...

def register_preference_generic(base_class, registry, *providers): # -> Callable[..., Any]:
    """Generic function to register a preference for a provider"""
    ...

