"""
This type stub file was generated by pyright.
"""

import abc
import dataclasses
import enum
import typing
from yt_dlp.extractor.youtube.pot._provider import IEContentProvider, IEContentProviderError
from yt_dlp.extractor.youtube.pot.provider import PoTokenRequest

"""PUBLIC API"""
class PoTokenCacheProviderError(IEContentProviderError):
    """An error occurred while fetching a PO Token"""
    ...


class PoTokenCacheProvider(IEContentProvider, abc.ABC, suffix='PCP'):
    @abc.abstractmethod
    def get(self, key: str) -> str | None:
        ...
    
    @abc.abstractmethod
    def store(self, key: str, value: str, expires_at: int): # -> None:
        ...
    
    @abc.abstractmethod
    def delete(self, key: str): # -> None:
        ...
    


class CacheProviderWritePolicy(enum.Enum):
    WRITE_ALL = ...
    WRITE_FIRST = ...


@dataclasses.dataclass
class PoTokenCacheSpec:
    key_bindings: dict[str, str | None]
    default_ttl: int
    write_policy: CacheProviderWritePolicy = ...
    _provider: PoTokenCacheSpecProvider | None = ...


class PoTokenCacheSpecProvider(IEContentProvider, abc.ABC, suffix='PCSP'):
    def is_available(self) -> bool:
        ...
    
    @abc.abstractmethod
    def generate_cache_spec(self, request: PoTokenRequest) -> PoTokenCacheSpec | None:
        """Generate a cache spec for the given request"""
        ...
    


def register_provider(provider: type[PoTokenCacheProvider]): # -> type[PoTokenCacheProvider]:
    """Register a PoTokenCacheProvider class"""
    ...

def register_spec(provider: type[PoTokenCacheSpecProvider]): # -> type[PoTokenCacheSpecProvider]:
    """Register a PoTokenCacheSpecProvider class"""
    ...

def register_preference(*providers: type[PoTokenCacheProvider]) -> typing.Callable[[CacheProviderPreference], CacheProviderPreference]:
    """Register a preference for a PoTokenCacheProvider"""
    ...

if typing.TYPE_CHECKING:
    CacheProviderPreference = typing.Callable[[PoTokenCacheProvider, PoTokenRequest], int]
