"""
This type stub file was generated by pyright.
"""

import typing
from yt_dlp.extractor.youtube.jsc.provider import JsChallengeProvider, JsChallengeProviderResponse, JsChallengeRequest, JsChallengeResponse, NChallengeInput, NChallengeOutput, Preference as JsChallengePreference, SigChallengeInput, SigChallengeOutput
from yt_dlp.extractor.youtube.pot._provider import IEContentProviderLogger

if typing.TYPE_CHECKING:
    ...
class JsChallengeRequestDirector:
    def __init__(self, logger: IEContentProviderLogger) -> None:
        ...
    
    def register_provider(self, provider: JsChallengeProvider): # -> None:
        ...
    
    def register_preference(self, preference: JsChallengePreference): # -> None:
        ...
    
    def bulk_solve(self, requests: list[JsChallengeRequest]) -> list[tuple[JsChallengeRequest, JsChallengeResponse]]:
        """Solves multiple JS Challenges in bulk, returning a list of responses"""
        ...
    
    def close(self): # -> None:
        ...
    


EXTRACTOR_ARG_PREFIX = ...
def initialize_jsc_director(ie): # -> JsChallengeRequestDirector:
    ...

def validate_provider_response(response: JsChallengeProviderResponse) -> bool:
    ...

def validate_response(response: JsChallengeResponse, request: JsChallengeRequest) -> bool | str:
    ...

def validate_nsig_challenge_output(challenge_output: NChallengeOutput, challenge_input: NChallengeInput) -> bool | str:
    ...

def validate_sig_challenge_output(challenge_output: SigChallengeOutput, challenge_input: SigChallengeInput) -> bool:
    ...

