"""
This type stub file was generated by pyright.
"""

import abc
import dataclasses
import enum
import typing
from yt_dlp.extractor.youtube.pot._provider import IEContentProvider, IEContentProviderError

"""PUBLIC API"""
__all__ = ['JsChallengeProvider', 'JsChallengeProviderError', 'JsChallengeProviderRejectedRequest', 'JsChallengeProviderResponse', 'JsChallengeRequest', 'JsChallengeResponse', 'JsChallengeType', 'NChallengeInput', 'NChallengeOutput', 'SigChallengeInput', 'SigChallengeOutput', 'register_preference', 'register_provider']
class JsChallengeType(enum.Enum):
    N = ...
    SIG = ...


@dataclasses.dataclass(frozen=True)
class JsChallengeRequest:
    type: JsChallengeType
    input: NChallengeInput | SigChallengeInput
    video_id: str | None = ...


@dataclasses.dataclass(frozen=True)
class NChallengeInput:
    player_url: str
    challenges: list[str] = ...


@dataclasses.dataclass(frozen=True)
class SigChallengeInput:
    player_url: str
    challenges: list[str] = ...


@dataclasses.dataclass(frozen=True)
class NChallengeOutput:
    results: dict[str, str] = ...


@dataclasses.dataclass(frozen=True)
class SigChallengeOutput:
    results: dict[str, str] = ...


@dataclasses.dataclass
class JsChallengeProviderResponse:
    request: JsChallengeRequest
    response: JsChallengeResponse | None = ...
    error: Exception | None = ...


@dataclasses.dataclass
class JsChallengeResponse:
    type: JsChallengeType
    output: NChallengeOutput | SigChallengeOutput
    ...


class JsChallengeProviderRejectedRequest(IEContentProviderError):
    """Reject the JsChallengeRequest (cannot handle the request)"""
    def __init__(self, msg=..., expected: bool = ..., *, _skipped_components=...) -> None:
        ...
    


class JsChallengeProviderError(IEContentProviderError):
    """An error occurred while solving the challenge"""
    ...


class JsChallengeProvider(IEContentProvider, abc.ABC, suffix='JCP'):
    _SUPPORTED_TYPES: tuple[JsChallengeType] | None = ...
    def bulk_solve(self, requests: list[JsChallengeRequest]) -> typing.Generator[JsChallengeProviderResponse, None, None]:
        """Solve multiple JS challenges and return the results"""
        ...
    


def register_provider(provider: type[JsChallengeProvider]): # -> type[JsChallengeProvider]:
    """Register a JsChallengeProvider class"""
    ...

def register_preference(*providers: type[JsChallengeProvider]) -> typing.Callable[[Preference], Preference]:
    """Register a preference for a JsChallengeProvider class."""
    ...

if typing.TYPE_CHECKING:
    Preference = typing.Callable[[JsChallengeProvider, list[JsChallengeRequest]], int]
