"""
This type stub file was generated by pyright.
"""

import os
from urllib.request import *

if os.name == 'nt':
    def getproxies_registry_patched():
        ...
    
    def getproxies(): # -> dict[str, str]:
        ...
    
