"""
This type stub file was generated by pyright.
"""

from .common import PostProcessor
from .embedthumbnail import EmbedThumbnailPP
from .exec import ExecAfterDownloadPP, ExecPP
from .ffmpeg import FFmpegConcatPP, FFmpegCopyStreamPP, FFmpegEmbedSubtitlePP, FFmpegExtractAudioPP, FFmpegFixupDuplicateMoovPP, FFmpegFixupDurationPP, FFmpegFixupM3u8PP, FFmpegFixupM4aPP, FFmpegFixupStretchedPP, FFmpegFixupTimestampPP, FFmpegMergerPP, FFmpegMetadataPP, FFmpegPostProcessor, FFmpegSplitChaptersPP, FFmpegSubtitlesConvertorPP, FFmpegThumbnailsConvertorPP, FFmpegVideoConvertorPP, FFmpegVideoRemuxerPP
from .metadataparser import MetadataFromFieldPP, MetadataFromTitlePP, MetadataParserPP
from .modify_chapters import ModifyChaptersPP
from .movefilesafterdownload import MoveFilesAfterDownloadPP
from .sponsorblock import SponsorBlockPP
from .xattrpp import XAttrMetadataPP
from ..globals import plugin_pps, postprocessors
from ..plugins import PACKAGE_NAME, PluginSpec, register_plugin_spec
from ..utils import deprecation_warning

def __getattr__(name): # -> Any:
    ...

def get_postprocessor(key): # -> Any:
    ...

_default_pps = ...
__all__ = list(_default_pps.values())
