"""
This type stub file was generated by pyright.
"""

import warnings
from .common import HEADRequest, PATCHRequest, PUTRequest, Request, RequestDirector, RequestHandler, Response
from . import _curlcffi, _requests, _urllib, _websockets
from ..utils import bug_reports_message

