"""
This type stub file was generated by pyright.
"""

import abc
from .common import RequestHandler, Response

class WebSocketResponse(Response):
    def send(self, message: bytes | str):
        """
        Send a message to the server.

        @param message: The message to send. A string (str) is sent as a text frame, bytes is sent as a binary frame.
        """
        ...
    
    def recv(self):
        ...
    


class WebSocketRequestHandler(RequestHandler, abc.ABC):
    ...


