"""
This type stub file was generated by pyright.
"""

from ._base import YoutubeBaseInfoExtractor
from ._clip import YoutubeClipIE
from ._mistakes import YoutubeTruncatedIDIE, YoutubeTruncatedURLIE
from ._notifications import YoutubeNotificationsIE
from ._redirect import YoutubeConsentRedirectIE, YoutubeFavouritesIE, YoutubeFeedsInfoExtractor, YoutubeHistoryIE, YoutubeLivestreamEmbedIE, YoutubeRecommendedIE, YoutubeShortsAudioPivotIE, YoutubeSubscriptionsIE, YoutubeWatchLaterIE, YoutubeYtBeIE, YoutubeYtUserIE
from ._search import YoutubeMusicSearchURLIE, YoutubeSearchIE, YoutubeSearchURLIE
from ._tab import YoutubePlaylistIE, YoutubeTabBaseInfoExtractor, YoutubeTabIE
from ._video import YoutubeIE

