"""
This type stub file was generated by pyright.
"""

from ._tab import YoutubeTabBaseInfoExtractor

class YoutubeClipIE(YoutubeTabBaseInfoExtractor):
    IE_NAME = ...
    _VALID_URL = ...
    _TESTS = ...


