"""
This type stub file was generated by pyright.
"""

import sys
import collections
import getpass
import itertools
import optparse
import os
import re
import traceback
from .cookies import CookieLoadError, SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
from .downloader.external import get_external_downloader
from .extractor import gen_extractors, list_extractor_classes, list_extractors
from .extractor.adobepass import MSO_INFO
from .networking.impersonate import ImpersonateTarget
from .globals import IN_CLI, plugin_dirs, supported_js_runtimes, supported_remote_components
from .options import parseOpts
from .plugins import load_all_plugins as _load_all_plugins
from .postprocessor import FFmpegExtractAudioPP, FFmpegMergerPP, FFmpegPostProcessor, FFmpegSubtitlesConvertorPP, FFmpegThumbnailsConvertorPP, FFmpegVideoConvertorPP, FFmpegVideoRemuxerPP, MetadataFromFieldPP, MetadataParserPP
from .update import Updater
from .utils import DateRange, DownloadCancelled, DownloadError, FormatSorter, GeoUtils, NO_DEFAULT, POSTPROCESS_WHEN, PlaylistEntries, SameFileError, download_range_func, expand_path, float_or_none, format_field, int_or_none, join_nonempty, match_filter_func, parse_bytes, parse_duration, preferredencoding, read_batch_urls, read_stdin, render_table, setproctitle, shell_quote, variadic, write_string
from .utils._utils import _UnsafeExtensionError
from .utils._jsruntime import BunJsRuntime as _BunJsRuntime, DenoJsRuntime as _DenoJsRuntime, NodeJsRuntime as _NodeJsRuntime, QuickJsRuntime as _QuickJsRuntime
from .YoutubeDL import YoutubeDL

if sys.version_info < (3, 10):
    ...
__license__ = ...
def get_urls(urls, batchfile, verbose): # -> list[str | Any]:
    """
    @param verbose      -1: quiet, 0: normal, 1: verbose
    """
    ...

def print_extractor_information(opts, urls): # -> bool:
    ...

def set_compat_opts(opts): # -> None:
    ...

def validate_options(opts): # -> tuple[list[Any], list[Any]]:
    ...

def get_postprocessors(opts): # -> Generator[Any | dict[str, str | Any] | dict[str, str | Any | bool] | dict[str, str], Any, None]:
    ...

ParsedOptions = ...
def parse_options(argv=...): # -> ParsedOptions:
    """@returns ParsedOptions(parser, opts, urls, ydl_opts)"""
    ...

def main(argv=...): # -> None:
    ...

__all__ = ['YoutubeDL', 'gen_extractors', 'list_extractors', 'main', 'parse_options']
