"""
This type stub file was generated by pyright.
"""

import collections
from .utils import ExtractorError

def int_to_int32(n):
    """Converts an integer to a signed 32-bit integer"""
    ...

def js_number_to_string(val: float, radix: int = ...): # -> str:
    ...

_OPERATORS = ...
_COMP_OPERATORS = ...
_NAME_RE = ...
_MATCHING_PARENS = ...
_QUOTES = ...
_NESTED_BRACKETS = ...
class JS_Undefined:
    ...


class JS_Break(ExtractorError):
    def __init__(self) -> None:
        ...
    


class JS_Continue(ExtractorError):
    def __init__(self) -> None:
        ...
    


class JS_Throw(ExtractorError):
    def __init__(self, e) -> None:
        ...
    


class LocalNameSpace(collections.ChainMap):
    def __setitem__(self, key, value): # -> None:
        ...
    
    def __delitem__(self, key):
        ...
    
    def set_local(self, key, value): # -> None:
        ...
    
    def get_local(self, key): # -> type[JS_Undefined]:
        ...
    


class Debugger:
    ENABLED = ...
    @staticmethod
    def write(*args, level=...): # -> None:
        ...
    
    @classmethod
    def wrap_interpreter(cls, f): # -> Callable[..., tuple[Any, Any]]:
        ...
    


class JSInterpreter:
    __named_object_counter = ...
    _RE_FLAGS = ...
    def __init__(self, code, objects=...) -> None:
        ...
    
    class Exception(ExtractorError):
        def __init__(self, msg, expr=..., *args, **kwargs) -> None:
            ...
        
    
    
    @Debugger.wrap_interpreter
    def interpret_statement(self, stmt, local_vars, allow_recursion=..., _is_var_declaration=...):
        ...
    
    def interpret_expression(self, expr, local_vars, allow_recursion):
        ...
    
    def extract_object(self, objname, *global_stack): # -> dict[Any, Any]:
        ...
    
    def extract_function_code(self, funcname): # -> tuple[list[str | Any], Any]:
        """ @returns argnames, code """
        ...
    
    def extract_function(self, funcname, *global_stack): # -> function_with_repr:
        ...
    
    def extract_function_from_code(self, argnames, code, *global_stack): # -> Callable[..., Any | None]:
        ...
    
    def call_function(self, funcname, *args):
        ...
    
    def build_function(self, argnames, code, *global_stack): # -> Callable[..., Any | None]:
        ...
    


