"""
This type stub file was generated by pyright.
"""

import dataclasses
import functools
import importlib
import importlib.abc
from .globals import Indirect

PACKAGE_NAME = ...
COMPAT_PACKAGE_NAME = ...
_BASE_PACKAGE_PATH = ...
__all__ = ['COMPAT_PACKAGE_NAME', 'PACKAGE_NAME', 'PluginSpec', 'directories', 'load_all_plugins', 'load_plugins', 'register_plugin_spec']
@dataclasses.dataclass
class PluginSpec:
    module_name: str
    suffix: str
    destination: Indirect
    plugin_destination: Indirect
    ...


class PluginLoader(importlib.abc.Loader):
    """Dummy loader for virtual namespace packages"""
    def exec_module(self, module): # -> None:
        ...
    


@functools.cache
def dirs_in_zip(archive): # -> set[Path] | tuple[()]:
    ...

def default_plugin_paths(): # -> Generator[Path, Any, None]:
    ...

def candidate_plugin_paths(candidate): # -> Generator[Path, Any, None]:
    ...

class PluginFinder(importlib.abc.MetaPathFinder):
    """
    This class provides one or multiple namespace packages.
    It searches in sys.path and yt-dlp config folders for
    the existing subdirectories from which the modules can be imported
    """
    def __init__(self, *packages) -> None:
        ...
    
    def search_locations(self, fullname): # -> Generator[Path, Any, None]:
        ...
    
    def find_spec(self, fullname, path=..., target=...): # -> ModuleSpec | None:
        ...
    
    def invalidate_caches(self): # -> None:
        ...
    


def directories(): # -> list[str] | list[Any]:
    ...

def iter_modules(subpackage): # -> Generator[ModuleInfo, Any, None]:
    ...

def get_regular_classes(module, module_name, suffix): # -> _GetMembersReturn[Any]:
    ...

def load_plugins(plugin_spec: PluginSpec): # -> dict[Any, Any]:
    ...

def load_all_plugins(): # -> None:
    ...

def register_plugin_spec(plugin_spec: PluginSpec): # -> None:
    ...

