"""
This type stub file was generated by pyright.
"""

import functools
from dataclasses import dataclass

UPDATE_SOURCES = ...
REPOSITORY = ...
_INVERSE_UPDATE_SOURCES = ...
_VERSION_RE = ...
_HASH_PATTERN = ...
_COMMIT_RE = ...
API_BASE_URL = ...
API_URL = ...
def detect_variant(): # -> Literal['pip']:
    ...

@functools.cache
def current_git_head(): # -> LiteralString | bytes | None:
    ...

_FILE_SUFFIXES = ...
_NON_UPDATEABLE_REASONS = ...
def is_non_updateable(): # -> Any | str | None:
    ...

@dataclass
class UpdateInfo:
    """
    Update target information

    Can be created by `query_update()` or manually.

    Attributes:
        tag                 The release tag that will be updated to. If from query_update,
                            the value is after API resolution and update spec processing.
                            The only property that is required.
        version             The actual numeric version (if available) of the binary to be updated to,
                            after API resolution and update spec processing. (default: None)
        requested_version   Numeric version of the binary being requested (if available),
                            after API resolution only. (default: None)
        commit              Commit hash (if available) of the binary to be updated to,
                            after API resolution and update spec processing. (default: None)
                            This value will only match the RELEASE_GIT_HEAD of prerelease builds.
        binary_name         Filename of the binary to be updated to. (default: current binary name)
        checksum            Expected checksum (if available) of the binary to be
                            updated to. (default: None)
    """
    tag: str
    version: str | None = ...
    requested_version: str | None = ...
    commit: str | None = ...
    binary_name: str | None = ...
    checksum: str | None = ...


class Updater:
    _channel = ...
    _origin = ...
    _update_sources = ...
    def __init__(self, ydl, target: str | None = ...) -> None:
        ...
    
    @property
    def current_version(self): # -> Literal['2026.03.17']:
        """Current version"""
        ...
    
    @property
    def current_commit(self): # -> Literal['04d6974f502bbdfaed72c624344f262e30ad9708']:
        """Current commit hash"""
        ...
    
    def query_update(self, *, _output=...) -> UpdateInfo | None:
        """Fetches info about the available update
        @returns   An `UpdateInfo` if there is an update available, else None
        """
        ...
    
    def update(self, update_info=...):
        """Update yt-dlp executable to the latest version
        @param update_info  `UpdateInfo | None` as returned by query_update()
        """
        ...
    
    @functools.cached_property
    def filename(self): # -> str:
        """Filename of the executable"""
        ...
    
    @functools.cached_property
    def cmd(self): # -> list[str]:
        """The command-line to run the executable, if known"""
        ...
    
    def restart(self): # -> int | Any:
        """Restart the executable"""
        ...
    


def run_update(ydl):
    """Update the program file with the latest version from the repository
    @returns    Whether there was a successful update (No update = False)
    """
    ...

__all__ = ['Updater']
